### ISSUE TITLE
Problem writing reverb settings over SysEx

### ISSUE THREAD

**Issue by peralmered** [munt/munt#101]
I've been successful writing to both the display and the master volume using SysEx from Cubase v3.1 on the Atari ST (emulated in STEem, an Atari ST emulator for Windows).

However, when I try to write to the reverb registers, nothing happens. I'm using the exact same process as when I write to the display and the master volume (and the master volume is even in the same address space as the reverb registers).

I'm starting to suspect this might be an issue with Munt itself.

For reference, the string I'm using to set master volume to 0 is (all hex):
`f0,41,10,16,12,10,00,16,00,5a,f7`
...and to set it to 100:
`f0,41,10,16,12,10,00,16,64,76,f7`
(you will notice the "data length" byte (a0 as the second byte in both strings above) is missing, but Cubase adds it in automatically)

String I'm using to try to change reverb mode to Plate reverb:
`f0,41,10,16,12,10,00,01,02,6d,f7`
...and I've tried other values for the data byte (02) too, but it made no difference.

I even found a forum post where someone claimed success changing to Tap delay with max volume and time using the three following SysEx strings, but they do nothing here either:
```
F0,41,10,16,12,10,00,01,04,6B,F7
F0,41,10,16,12,10,00,02,08,66,F7
F0,41,10,16,12,10,00,03,08,65,F7
```

Per.

**Comment by sergm** [comment]
The described behaviour is possible to reproduce, although it is not enabled by default. Historically, the mt32emu API provided a way of setting custom reverb settings for the client, so that any reverb settings set via SysEx messages are ignored. See the related [API function](https://github.com/munt/munt/blob/master/mt32emu/src/Synth.h#L406).

Similarly, mt32emu-qt implements such a reverb override mode. Unless the "Reverb Enabled" checkbox in the Synth Properties dialog remains in the default "grey" state, any attempt to alter reverb settings via a SysEx message has no effect. Instead, the reverb is ether always disabled or always remains enabled with the reverb settings set via the UI.

Please see if this info helps.

**Comment by peralmered** [comment]
You're absolutely right, if I just start munt "fresh" and load my MIDI file, it **does** accept reverb settings over SysEx. I must have simply messed around with it and not just realized the "greyed out" mode of the button had that effect.

It _might_ be a good idea to change the UI - maybe add a 2nd checkbox for "allow SysEx to modify reverb settings"?

**Comment by sergm** [comment]
IMHO, there're enough checkboxes within already to confuse people :smile: 
But I think we nevertheless must add tooltips to those controls which currently lack any description.
