### ISSUE TITLE
is there any documentation on how to use mt32emu?

### ISSUE THREAD

**Issue by Raffaello** [munt/munt#113]
is there any documentation or even a plan just to add a documentation in the APIs in the C and C++ interfaces of mt32emu?

I find quite challenging already to understand what is the difference among:

- addRomFiles
- addRomData

as a for name i will say the first is doing the same as the second but it loads the data from file, while the 2nd instead it takes from memory so a client already pre-loaded the data from files.
but....
addRomData looking at its implementation is using addRomFiles making my above absumption/deduction wrong.

So, i am wondering if there is some documentation to give some hint to program the mt32emu that i didn't discovered yet.
Is there any links to such documentation?
Any possibilities to plan to add documentation (kinda docygen related) in the APIs interface at least?

**Comment by sergm** [comment]
Yes, you can find quite some useful hints on what the provided C functions do by looking at [the header file](https://github.com/munt/munt/blob/master/mt32emu/src/c_interface/c_interface.h). The C++ wrapper for that API is unfortunately not well documented, so one should look at the C interface for reference. The plan is to introduce code generation for the most boring part of the C++ wrapper, so that IDEs will easily pick the related documentation for the methods of the `Service` class.

Speaking of the two methods `addRomFiles` and `addRomData`, you already guessed right. See [the description of `addRomData`](https://github.com/munt/munt/blob/master/mt32emu/src/c_interface/c_interface.h#L136-L146) and [the description of `addRomFiles`](https://github.com/munt/munt/blob/master/mt32emu/src/c_interface/c_interface.h#L148-L155). A look at the implementation might seem a bit misleading, but in fact both ways work with files; we just wrap the data array into a virtual file. This is similar to how it is done in scummvm, for example.

As for the use of tooling like doxygen to create isolated documentation in HTML form, that'd probably not be very useful. Making the stand-alone documentation useful would rather imply increasing the amount of information within, and the amount of the duplicated information in the documentation somewhat exceeds the necessity already, I think. Hopefully, modern C++ IDEs allow us to live happily without such things.

**Comment by Raffaello** [comment]
thanks! yes the C interface docs is good enough.
