### ISSUE TITLE
[Feature] Integrate a patch editor into the Qt GUI

### ISSUE THREAD

**Issue by TheMisterE** [munt/munt#76]
_**The pitch**_
I've been bashing my head against the wall for months now trying to make MT-32 patches by routing the handful of patch editors that support the MT-32 into MUNT (both the Qt Standalone or Falcosoft's VSTi), and all I've gotten from it was lost hours and clumps of hair.

Figuring out how to send SYSEX commands... How to formulate a MT-32 SYSEX command... Trying to send anything from the editor to the software usually to no avail... And that's when it hit me.

_**The execution**_
If MUNT is emulating the MT-32, wouldn't it be trivial to directly modify the registers without jumping through any hoops at all? I can imagine a GUI function of double clicking a channel, seeing a nice and fancy editing screen, and editing the memory itself all in real time. No fuss, no muss, no MIDI commands at all.

In fact, I could also see a part of that GUI neatly providing a means of exporting well... anything as a SYSEX MIDI/.syx file.
It would read the state of the timbre/patch/bank in the editor, but not in the MT-32's memory itself (unless you want to take such an approach), and provide a choice of exporting the parameters in a singular SYSEX by itself or as a string of SYSEX commands for initializing and writing multiple timbres into the MT-32's memory for a whole song, everything all ready to go and waiting to be sequenced.

_**The summary**_
However you slice it, making patches for the MT-32 these days, _especially_ internally in software using MUNT, is an exercise in convolutedness and futility. There's already a perfectly good Qt GUI interfacing MUNT as a whole, and an earlier suggestion of using the Qt GUI to select the preset timbres was received well. Why not go whole hog?

**Comment by TheMisterE** [comment]
I was just thinking that there would be no MIDI command overflow risk during real time editing, like knob adjusting during playback, if the commands aren't flooding in on the same line as the rest of the commands.

Anyway, here's hoping somebody saves us (and more specifically me) from the Sisyphean effort of making MT-32 timbres on modern hardware, much less all in-system with MUNT.

...Guess now this means I have no choice but to see if I can do such a thing in ReaLearn. _**Ugh.**_

**Comment by now-its-dark** [comment]
@TheMisterE, I feel your pain— having gone fairly deep down this rabbit hole over the past couple years myself. What I have found to work best, is the last stable release of the abandoned SoundDiver. It is easy to find on archive.org and will run stably on modern Windows or WINE; It comes with a well designed adaptation (SD name for editor panel) for the MT-32, including librarian functions and drum mapping. There is some jank, but works pretty reliably, once you get to know the quirks. See img below for an example of the UI.

The archived ver. of Seald's Deep Synthesis has an alternate, [simplified adaptation](http://web.archive.org/web/20100402230016/http://homepage.mac.com/synth_seal/html/mt32c.html); it is faster to use, but more limited. This is helpful in another way though, because it includes default patch / setup configs, so you can begin as though the editor received an initial dump from the synth— Since MUNT does not report the current patches or parameter settings in memory, the connection is unidirectional. To mitigate that, just keep the auto-update function enabled, then MUNT will  always match your editor state.

Planning to make a video/tutorial for this workflow pretty soon!

———
Regarding the question of whether there is a real desire to edit this device in general— from what I've seen online, people typically regard the MT-32 as a barebones, proto-GM rompler with limited creative potential in terms of sound design. Presumably, this is  due to having no contemporary software editor or on-device editing capabilities and the amount of cheesy presets onboard. 

Having spent some time editing it now, I think it is severely underestimated as a synthesizer. The depth of the voice architecture and level of configurability are really impressive in that form-factor, especially for a device from the late 80's. 

Wow that was lengthy, hope it is helpful information for you and anyone else who stumbles onto this discussion.

<img width="963" alt="SoundDiver_MT32" src="https://user-images.githubusercontent.com/5728860/153307653-9bb23ce5-1b5b-4a17-845c-7f5c98a9fb62.png">

**Comment by sergm** [comment]
Right, that's all fair enough. I myself have been using an abandoned LA-SYNTH editor running in a VM (as that's a win16 thing) to play with some edge cases which is not a way to go for professional work. Definitely, these synths feature great configurability, else we'd not bother with the emulation. So, as I said above, a good modern patch editor is needed, but rather as a stand-alone app. IMHO, such an editor would support whatever you connect: either munt or a real device via MIDI.

**Comment by now-its-dark** [comment]
@sergm Yep that makes total sense! An editing capability would be a pretty distinct use-case from the PC gaming crowd. I wasn't trying to propose anything development-wise, just outlining a relatively modern and usable way to edit it currently, for the sake of anyone who is looking for one. Not a topic that comes up too often, so seemed worthwhile to explain these findings.

**Comment by joerg-knitter** [comment]
I also took a deeper look into the synthesis feature, and I even was not aware that the MT-32 is a kind of smaller sibling to the legandary D-50, even though the samples are limited/worse and I think there was just one LFO instead of 3, but the MT-32 is multi-timbral on the other side while the D-50 can only play 2 different sounds at one time. Therefore, it could also e.g. very interesting to the demo scene where GM/GS is too limited, FM too bad and samples too memory hungry.

One of the main issues I discovered and checked with the source code (sorry, I am just able to partly understand source code, but I am not able to fix it myself) is that a lot of tested editors fail because MUNT only supports the DT1 command but none of the other commands (WSD, RQD, DAT, EOD...), so using commands where handshaking is involved do not work. Therefore, as written by someone before, even getting a memory dump right at the start of an editor causes an error message.
If this could be fixed, one might use at any editor out there, but I did fail with the ones I found in DOSBox (DOS and Windows 3.x) apart from SoundDiver that I did not check yet, so thanks for this hint. However, adding the missing MIDI functionality could at least be a great opportunity to get more people interested, especially if they knew that the MT-32 is not only a "stupid sample player"...

I had a look at ctrlr from www.ctrlr.org. It could be a great solution because it is not only a stand-alone controller for MIDI devices, but can also be used as VST3 instrument in a DAW. It is open-source and platform independent.
But: It is kind-of undocumented - apart from 9 year old examples, the C++ source code and discussions on the forum (closed) and GitHub. There is no Wiki (yet) and only <10 basic tutorials on YouTube. The UI for creating panels is awful, and for sending the required syx commands, you would have to use LUA commands and not something more common nowadays like Python. Maybe doing some copy & paste from the example panels might help here creating something. And the project is not dead (yet).
On the other hand, I am sure that is possible to create an MT32 panel witih ctrlr - if there was not that deep learning curve...

**Comment by sergm** [comment]
Good new, BTW! A new project appeared on the scene quite recently called [MT32Editor](https://github.com/sfryers/MT32Editor). I suppose, this is more or less what one needs to unleash creativity with MT-32 (at least @now-its-dark seems happy with it, heh). There is just one thing to note, this is Windows-only atm.

FYI, there is also a thread at [VOGONS](https://www.vogons.org/viewtopic.php?f=29&t=93609) dedicated on this nice tool.

**Comment by TheMisterE** [comment]
Oh my god. It works with MUNT! It really works! It's not even done and it works!!

Send out the good word far and wide, christen https://github.com/sfryers with a medal or something! WE HAVE AN EDITOR THAT WORKS WITH MUNT!!

**Comment by sergm** [comment]
> WE HAVE AN EDITOR THAT WORKS WITH MUNT!!

Well, on Windows at least 🙂
