### ISSUE TITLE
SC-55 emulation

### ISSUE THREAD

**Issue by Kappa971** [munt/munt#78]
MUNT is a very accurate emulator as far as the Roland MT-32 is concerned, unfortunately the Roland SC-55 currently doesn't have an emulator. There are many soundfonts that try to imitate it but fail in many ways. 
Almost a year ago progress was made for decoding ROMs in this forum: https://www.vogons.org/viewtopic.php?f=62&t=76613&start=320, a tool was created to convert ROMs to soundfont .sf2 (https://github.com/Kitrinx/SC55_Soundfont) but since then everything has stood still, and in any case the developer himself has admitted that the .sf2 format is unable to accurately express the SC-55.

**Comment by sergm** [comment]
Hmm, I am not really following. How is that Roland SC-55 does not have an emulator? AFAIK, there is more than one, yet provided by the original vendor, so I don't see any problems with that.

Additional note: the GS devices are substantially different when comparing to the LA devices. I barely see **any** part of munt code that could be reused in a GS emulator, even if one was developed. Therefore, talks about emulation of any GS device are definitely out of the context of munt.

**Comment by Kappa971** [comment]
> Hmm, I am not really following. How is that Roland SC-55 does not have an emulator? AFAIK, there is more than one, yet provided by the original vendor, so I don't see any problems with that.

I know but it costs more than € 100/$ 100, it isn't free (unless you go into illegality) and it doesn't emulate the SC-55 but the SC-8820, with the possibility to choose the instruments of the SC -55, but it is far from accurate.

> Therefore, talks about emulation of any GS device are definitely out of the context of munt.

the MT-32 had a fantastic emulator that allows everyone to listen to the video game music created with it, while also preserving its history, the SC-55 (in my opinion of equal importance) did not receive the same treatment. Since there is no interest, thanks anyway.

**Comment by Kitrinx** [comment]
FWIW, While Roland does supply some emulators for sc-55, I don't know of one that is full quality. Sound Canvas VA is an SC-88 emulator, and also extremely expensive. LA and Sound Canvas line do work substantially differently, however I think you would be surprised by the amount of overlap in the envelope handling. SC-55 shares the same three TVP/TVA/TVF envelopes with a similar five point system. I'm sure the tables are different, but there's enough overlap that it's really not entirely out of scope, especially since one device actually combined the two together.

**Comment by Kappa971** [comment]
Exactly. As mentioned, it emulates the SC-8820 with the ability to set the instruments of the SC-55 but doesn't sound the same, besides the fact that it isn't meant to be used for video games but for music creation software. Plus the prohibitive cost, (now a subscription is required) unless you switch to pirated software. I speak as a gamer, @Kitrinx knows more than me about the technical aspects being a programmer.

**Comment by Kappa971** [comment]
Anyway @Kitrinx I think that, if you have time and desire to start such a project, you could open a fork of MUNT and "readjust" it for the SC-55 (as I understand it, most of the code should be rewritten). In this way, anyone who wants to could contribute to the project (perhaps even those of Vogons). If you don't have time or desire, no problem, thanks anyway :)

**Comment by Kitrinx** [comment]
The reason I did the work to decrypt and map out the various tables in the control rom was because of our 486 core, there really was no reasonable sc-55 option to use other than real hardware, which made me sad. mt32pi did well with it's munt port, but the best there was for gs/gm was fluidsynth. While fluidsynth is very good for general purpose GM, the soundfont format is not complex enough to properly emulate sc-55, it really needs its own emulator to be able to act like the real hardware for games like Descent and etc that really on having the correct synth to sound good.

**Comment by Kappa971** [comment]
@sergm immediately closed the issue without any discussion so I don't think he is interested in implementing it in MUNT. 
At this point I hope someone will fork MUNT for SC-55. Maybe you could open a topic in vogons to bring together a group of people interested and able to do something like that. Thanks anyway :)

**Comment by DMJC** [comment]
The EmuSC project already exists for this issue: https://github.com/skjelten/emusc

**Comment by Kitrinx** [comment]
It does now, because munt wanted nothing to do with it.

**Comment by nickkeane** [comment]
Nukeykt is currently working on an SC-55 emulator from a snapshot of a delidded mkII.

https://github.com/nukeykt/Nuked-SC55

**Comment by Karmeck** [comment]
> Nuked is currently working on an SC-55 emulator from a snapshot of a delidded mkII chip.
> 
> https://github.com/nukeykt/Nuked-SC55

it's now released.
