### ISSUE TITLE
[Feature] Play the demo

### ISSUE THREAD

**Issue by nikitalita** [munt/munt#84]
I'm not sure if it's currently enabled or not (searching for "demo" doesn't return anything), but it would be nice to be able to trigger the demo mode and play the demo songs that are stored in the rom. Is this possible?

**Comment by sergm** [comment]
Currently, there is no support for playing demo songs in this emulator. It seems, this feature initially had a low-priority from start, yet those demo songs are only present in a few control ROM versions. For instance, these won't be available should one use the old-gen MT-32 control ROM v1.07 or the CM-32L ROMs. Albeit, I hope this won't be too difficult to implement an interpreter for the demo song format, which looks very much SMF-like. Will look at it in mid-term 🙂

**Comment by nikitalita** [comment]
How did the MT-32 itself parse them? Was it in the control rom, or was it handled by a separate microcontroller?

**Comment by sergm** [comment]
Evidently, the player code resides in the control ROM. Moreover, it is there even in CM-32L ROM, despite there are no demo songs within in that version.

**Comment by nikitalita** [comment]
Are the songs stored in SMF format, or something close to it?

**Comment by sergm** [comment]
> Are the songs stored in SMF format, or something close to it?

It is definitely something very close and based on MIDI messages of course, but it doesn't resemble the content of a SMF MIDI track in full. In particular, I noticed that long pauses between messages are not encoded with the help of variable-length fields, yet the end-of-track marker is definitely non-standard. But the main problem here is the instrument mapping, since playing these messages using the standard MT-32 patch map sounds rather odd...

**Comment by nikitalita** [comment]
Wait, I think I closed this by accident, is this implemented?

**Comment by nikitalita** [comment]
It's implemented, and a snapshot build is available here: https://sourceforge.net/projects/munt/files/munt/SNAPSHOTS/Windows/mt32emu_qt-1.11-git613c0ea765-amd64.zip/download

Thanks!
