### ISSUE TITLE
The geometry of the floating LCD can become inaccessible

### ISSUE THREAD

**Issue by ParticleMon** [munt/munt#94]
In Cinnamon on Linux with multiple displays and the floating LCD on a secondary display at a window position beyond the resolution of the primary display, deactivating or disconnecting the secondary display moves the LCD to the primary display as expected but at an inaccessible window position.

Reproduction:
1. In Cinnamon on Linux, connect a secondary display having a resolution higher than the primary display.
2. Move the floating LCD to the secondary display beyond the comparable range of the primary display (such as to the bottom right corner).
3. Disconnect the secondary display.

The floating LCD is not visible on the primary display.

To restore the visibility of and accessibility to the LCD, activate or connect the secondary display.

Moreover, placing the LCD over a panel prevents the LCD from responding to left and right clicks, thus from being moved.

To restore access to move the LCD, modify the geometry value in ~/.config/muntemu.org/'Munt mt32emu-qt.conf' to a value within the range of the display that is beyond visible panel areas.

mt32emu_qt 2.7 AppImage | Cinnamon 5.2.7 | Linux Mint 20.3

**Comment by sergm** [comment]
Right, the floating window does not change its position in response on a change of screen configuration by default. Neither it is movable when placed over a panel or some other special areas that desktop manager controls. However, these are not the only problems I've experienced while testing it with various desktop environments, the behaviour depends mostly on whether the desktop manager controls the floating window or not. In my tests, both options appeared not ideal, so I simply added an option to let the user decide which one is preferred (see the attached screenshot).

![Screen](https://user-images.githubusercontent.com/665378/171989389-0d958708-9b05-4e2b-9572-d3927625b014.png)

I haven't tested whether disabling the option "Bypass window manager" actually helps with the first test case but there is a good chance for it. Although, there is likely a way to improve the behaviour even when the window manager is bypassed, at least with modern Qt versions. Sadly, the related Qt API has changed dramatically since Qt 4 which we still want to support to make the application available on older systems. I'll look closer at it shortly.

**Comment by sergm** [comment]
I can confirm that making the floating window managed by the window manager ensures the desired behaviour at least on Plasma. But OTOH, the latter does not suffer from the panel issue you've mentioned...

**Comment by sergm** [comment]
Also note, the floating window must be re-positioned within the visible extents of the desktop by merely restarting mt32emu-qt, there should be no need to edit the configuration file manually. Again, this is how it works on Windows and Plasma...

**Comment by ParticleMon** [comment]
I've kept "Bypass" enabled to work around a certain issue. However, I'm not able to replicate this issue now. Since previous testing, I've restarted the DE, which seems to have fixed the issue(s).

FWIW, the state in which Cinnamon had been when manifesting the above, restarting mt32emu-qt did not fix the issue, regardless, I think, of the "Bypass" setting.

I like Cinnamon but its quirks can be irksome, especially with multiple displays.

**Comment by sergm** [comment]
Yeah, it's hard to find a perfect free DE unless you're the developer of it 😉

But still, as I tested this stuff more in some particularly evil configurations, like two screens set up with different scale factor, etc., it reveal a couple of things that are definitely should be improved. So thanks for driving my attention to multi-display stuff anyway!
